# Generated by Django 2.1.5 on 2019-02-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(default=0, max_length=4096),
            preserve_default=False,
        ),
    ]
