# Generated by Django 2.1.5 on 2019-02-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190204_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
