# Generated by Django 2.1.5 on 2019-02-03 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='height',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(32), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='game',
            name='width',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(32), django.core.validators.MinValueValidator(8)]),
        ),
    ]
