# Generated by Django 2.1.5 on 2019-02-03 23:31

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190203_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_state',
            field=models.CharField(choices=[('S', 'Started'), ('W', 'Won'), ('L', 'Lost')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(default=game.models.generate_serialized_game_with_defaults, max_length=4096),
        ),
    ]
